name: Generate Container

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      container_id: ${{ steps.generate_id.outputs.container_id }}

    steps:
      - name: Generate Container ID
        id: generate_id
        run: |
          CONTAINER_ID="container-$(date +%s)"
          echo "Generated container ID: $CONTAINER_ID"
          echo "::set-output name=container_id::$CONTAINER_ID"

      - name: Save Container ID
        run: |
          echo ${{ steps.generate_id.outputs.container_id }} > scripts/container_id.txt
