name: Generate Container

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate container ID
        id: generate
        run: |
          CONTAINER_ID="demo-$(date +%s)"
          echo "Generated container ID: $CONTAINER_ID"
          # Save to workflow output
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT

      - name: Set repository environment variable
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: set-container-env
          client-payload: '{"container_id":"${{ steps.generate.outputs.container_id }}"}'
