name: Generate Container

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate container ID
        id: generate
        run: |
          CONTAINER_ID="demo-${RANDOM}"
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT
          echo "Generated container ID: $CONTAINER_ID"

      - name: Trigger Polling Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
         token: ${{ secrets.PAT_TOKEN }}   # instead of GITHUB_TOKEN
         event-type: poll-container-url
         client-payload: |
          {
           "pr_number": "${{ github.event.pull_request.number }}",
           "container_id": "${{ steps.generate.outputs.container_id }}"
           "repository": "${{ github.repository }}",
           "organization": "${{ github.repository_owner }}"
          }
