name: Generate Container

on:
  workflow_dispatch:

# Grant permissions to trigger repository_dispatch
permissions:
  contents: read
  actions: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate container ID
        id: generate
        run: |
          CONTAINER_ID="demo-$(date +%s)"
          echo "Generated container ID: $CONTAINER_ID"
          # Save for output
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT

      - name: Trigger Poll Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"start_poll","client_payload":{"container_id":"'"${{ steps.generate.outputs.container_id }}"'"}}'
