name: Generate Container

on:
  workflow_dispatch:  # Manual trigger to generate container ID

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      container_id: ${{ steps.generate.outputs.container_id }}
    steps:
      - name: Generate container ID
        id: generate
        run: |
          CONTAINER_ID="demo-$(date +%s)"
          echo "Generated container ID: $CONTAINER_ID"
          # Pass container ID as workflow output
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT

      - name: Display container ID
        run: echo "Container ID is ${{ steps.generate.outputs.container_id }}"
